-- PUBLIC."USER" definition

-- Drop table

-- DROP TABLE PUBLIC."USER";

CREATE TABLE PUBLIC."USER" (
	ID VARCHAR(255) NOT NULL,
	ACTIVE BOOLEAN,
	CREATED_DATE TIMESTAMP,
	EMAIL VARCHAR(255),
	LAST_LOGIN TIMESTAMP,
	MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	TOKEN VARCHAR(255),
	CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_2 ON PUBLIC."USER" (ID);


-- PUBLIC.PHONE definition

-- Drop table

-- DROP TABLE PUBLIC.PHONE;

CREATE TABLE PUBLIC.PHONE (
	ID VARCHAR(255) NOT NULL,
	CITY_CODE VARCHAR(255),
	COUNTRY_CODE VARCHAR(255),
	"NUMBER" VARCHAR(255),
	ID_USER VARCHAR(255),
	CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID),
	CONSTRAINT FKBTCLSGMCQ82GWKCWM7MS1GINV FOREIGN KEY (ID_USER) REFERENCES PUBLIC."USER"(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX FKBTCLSGMCQ82GWKCWM7MS1GINV_INDEX_4 ON PUBLIC.PHONE (ID_USER);
CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PUBLIC.PHONE (ID);
